---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple

loggers:
  mediafelt:
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]
